/*
 * GLAD - OpenGL Loader Generated by glad 0.1.36 on the GLAD web service.
 *
 * Language/Generator: C/C++
 * Specification: gl
 * APIs: gl=3.3
 * Profile: core
 * Extensions: none
 * Loader: True
 *
 * Commandline:
 *   --profile="core" --api="gl=3.3" --generator="c" --spec="gl" --extensions=""
 *
 * Online:
 *   https://glad.dav1d.de/#profile=core&language=c&specification=gl&api=gl%3D3.3
 */
#ifndef GLAD_H_
#define GLAD_H_

/* Prevent Windows GL/gl.h from being included */
#define __gl_h_
#define __GL_H__
#define _GL_H
#define __gl_gl_h_

#include <KHR/khrplatform.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ========== OpenGL type definitions ========== */
typedef void            GLvoid;
typedef unsigned int    GLenum;
typedef khronos_float_t GLfloat;
typedef int             GLint;
typedef int             GLsizei;
typedef unsigned int    GLbitfield;
typedef double          GLdouble;
typedef unsigned int    GLuint;
typedef unsigned char   GLboolean;
typedef khronos_uint8_t GLubyte;
typedef khronos_float_t GLclampf;
typedef double          GLclampd;
typedef khronos_ssize_t GLsizeiptr;
typedef khronos_intptr_t GLintptr;
typedef char            GLchar;
typedef khronos_int16_t GLshort;
typedef khronos_int8_t  GLbyte;
typedef khronos_uint16_t GLushort;
typedef khronos_uint16_t GLhalf;
typedef struct __GLsync* GLsync;
typedef khronos_uint64_t GLuint64;
typedef khronos_int64_t  GLint64;

/* Callback for debug */
typedef void (KHRONOS_APIENTRY *GLDEBUGPROC)(GLenum source, GLenum type, GLuint id,
    GLenum severity, GLsizei length, const GLchar* message, const void* userParam);

/* Function pointer type for loading */
typedef void* (*GLADloadproc)(const char* name);

/* ========== Constants ========== */

/* Boolean */
#define GL_FALSE                        0
#define GL_TRUE                         1

/* Data types */
#define GL_BYTE                         0x1400
#define GL_UNSIGNED_BYTE                0x1401
#define GL_SHORT                        0x1402
#define GL_UNSIGNED_SHORT               0x1403
#define GL_INT                          0x1404
#define GL_UNSIGNED_INT                 0x1405
#define GL_FLOAT                        0x1406

/* Primitives */
#define GL_POINTS                       0x0000
#define GL_LINES                        0x0001
#define GL_LINE_LOOP                    0x0002
#define GL_LINE_STRIP                   0x0003
#define GL_TRIANGLES                    0x0004
#define GL_TRIANGLE_STRIP               0x0005
#define GL_TRIANGLE_FAN                 0x0006

/* Clear */
#define GL_DEPTH_BUFFER_BIT             0x00000100
#define GL_STENCIL_BUFFER_BIT           0x00000400
#define GL_COLOR_BUFFER_BIT             0x00004000

/* Textures */
#define GL_TEXTURE_2D                   0x0DE1
#define GL_TEXTURE0                     0x84C0
#define GL_TEXTURE_MIN_FILTER           0x2801
#define GL_TEXTURE_MAG_FILTER           0x2800
#define GL_TEXTURE_WRAP_S               0x2802
#define GL_TEXTURE_WRAP_T               0x2803
#define GL_NEAREST                      0x2600
#define GL_LINEAR                       0x2601
#define GL_CLAMP_TO_EDGE                0x812F
#define GL_REPEAT                       0x2901

/* Pixel formats */
#define GL_RED                          0x1903
#define GL_RGB                          0x1907
#define GL_RGBA                         0x1908
#define GL_RGB8                         0x8051
#define GL_RGBA8                        0x8058

/* Buffers */
#define GL_ARRAY_BUFFER                 0x8892
#define GL_ELEMENT_ARRAY_BUFFER         0x8893
#define GL_STATIC_DRAW                  0x88E4
#define GL_DYNAMIC_DRAW                 0x88E8

/* Shaders */
#define GL_FRAGMENT_SHADER              0x8B30
#define GL_VERTEX_SHADER                0x8B31
#define GL_COMPILE_STATUS               0x8B81
#define GL_LINK_STATUS                  0x8B82
#define GL_INFO_LOG_LENGTH              0x8B84

/* GetString */
#define GL_VENDOR                       0x1F00
#define GL_RENDERER                     0x1F01
#define GL_VERSION                      0x1F02
#define GL_EXTENSIONS                   0x1F03

/* Enable/Disable */
#define GL_DEPTH_TEST                   0x0B71
#define GL_BLEND                        0x0BE2
#define GL_CULL_FACE                    0x0B44

/* Blend */
#define GL_ZERO                         0
#define GL_ONE                          1
#define GL_SRC_COLOR                    0x0300
#define GL_ONE_MINUS_SRC_COLOR          0x0301
#define GL_SRC_ALPHA                    0x0302
#define GL_ONE_MINUS_SRC_ALPHA          0x0303
#define GL_DST_ALPHA                    0x0304
#define GL_ONE_MINUS_DST_ALPHA          0x0305
#define GL_DST_COLOR                    0x0306
#define GL_ONE_MINUS_DST_COLOR          0x0307

/* Errors */
#define GL_NO_ERROR                     0
#define GL_INVALID_ENUM                 0x0500
#define GL_INVALID_VALUE                0x0501
#define GL_INVALID_OPERATION            0x0502
#define GL_OUT_OF_MEMORY                0x0505

/* Misc state */
#define GL_NONE                         0
#define GL_FRONT                        0x0404
#define GL_BACK                         0x0405
#define GL_FRONT_AND_BACK               0x0408
#define GL_CW                           0x0900
#define GL_CCW                          0x0901
#define GL_LINE_WIDTH                   0x0B21
#define GL_SCISSOR_TEST                 0x0C11
#define GL_PACK_ALIGNMENT               0x0D05
#define GL_UNPACK_ALIGNMENT             0x0D06
#define GL_MAX_TEXTURE_SIZE             0x0D33

/* Polygon mode */
#define GL_POINT                        0x1B00
#define GL_LINE                         0x1B01
#define GL_FILL                         0x1B02

/* Depth */
#define GL_NEVER                        0x0200
#define GL_LESS                         0x0201
#define GL_EQUAL                        0x0202
#define GL_LEQUAL                       0x0203
#define GL_GREATER                      0x0204
#define GL_NOTEQUAL                     0x0205
#define GL_GEQUAL                       0x0206
#define GL_ALWAYS                       0x0207

/* Stencil */
#define GL_KEEP                         0x1E00
#define GL_REPLACE                      0x1E01
#define GL_INCR                         0x1E02
#define GL_DECR                         0x1E03

/* String queries */
#define GL_SHADING_LANGUAGE_VERSION     0x8B8C
#define GL_NUM_EXTENSIONS               0x821D

/* Additional texture formats */
#define GL_R8                           0x8229
#define GL_R16                          0x822A
#define GL_RG8                          0x822B
#define GL_RG16                         0x822C
#define GL_R16F                         0x822D
#define GL_R32F                         0x822E
#define GL_RG16F                        0x822F
#define GL_RG32F                        0x8230
#define GL_RGBA32F                      0x8814
#define GL_RGB32F                       0x8815
#define GL_RGBA16F                      0x881A
#define GL_RGB16F                       0x881B
#define GL_RG                           0x8227
#define GL_DEPTH_COMPONENT              0x1902
#define GL_DEPTH_COMPONENT16            0x81A5
#define GL_DEPTH_COMPONENT24            0x81A6
#define GL_DEPTH_COMPONENT32F           0x8CAC
#define GL_DEPTH_STENCIL                0x84F9

/* Texture types */
#define GL_TEXTURE_1D                   0x0DE0
#define GL_TEXTURE_3D                   0x806F
#define GL_TEXTURE_CUBE_MAP             0x8513
#define GL_TEXTURE_2D_ARRAY             0x8C1A
#define GL_TEXTURE_2D_MULTISAMPLE       0x9100

/* Texture parameters extra */
#define GL_NEAREST_MIPMAP_NEAREST       0x2700
#define GL_LINEAR_MIPMAP_NEAREST        0x2701
#define GL_NEAREST_MIPMAP_LINEAR        0x2702
#define GL_LINEAR_MIPMAP_LINEAR         0x2703
#define GL_TEXTURE_BASE_LEVEL           0x813C
#define GL_TEXTURE_MAX_LEVEL            0x813D
#define GL_MIRRORED_REPEAT              0x8370
#define GL_CLAMP_TO_BORDER              0x812D
#define GL_TEXTURE_WRAP_R               0x8072

/* Framebuffer */
#define GL_FRAMEBUFFER                  0x8D40
#define GL_READ_FRAMEBUFFER             0x8CA8
#define GL_DRAW_FRAMEBUFFER             0x8CA9
#define GL_RENDERBUFFER                 0x8D41
#define GL_COLOR_ATTACHMENT0            0x8CE0
#define GL_DEPTH_ATTACHMENT             0x8D00
#define GL_STENCIL_ATTACHMENT           0x8D20
#define GL_DEPTH_STENCIL_ATTACHMENT     0x821A
#define GL_FRAMEBUFFER_COMPLETE         0x8CD5

/* Buffer usage */
#define GL_STREAM_DRAW                  0x88E0
#define GL_STREAM_READ                  0x88E1
#define GL_STREAM_COPY                  0x88E2
#define GL_STATIC_READ                  0x88E5
#define GL_STATIC_COPY                  0x88E6
#define GL_DYNAMIC_READ                 0x88E9
#define GL_DYNAMIC_COPY                 0x88EA

/* Buffer targets */
#define GL_UNIFORM_BUFFER               0x8A11
#define GL_COPY_READ_BUFFER             0x8F36
#define GL_COPY_WRITE_BUFFER            0x8F37

/* Uniform types */
#define GL_FLOAT_VEC2                   0x8B50
#define GL_FLOAT_VEC3                   0x8B51
#define GL_FLOAT_VEC4                   0x8B52
#define GL_FLOAT_MAT2                   0x8B5A
#define GL_FLOAT_MAT3                   0x8B5B
#define GL_FLOAT_MAT4                   0x8B5C

/* Draw buffers */
#define GL_MAX_DRAW_BUFFERS             0x8824
#define GL_DRAW_BUFFER0                 0x8825

/* Multisample */
#define GL_MULTISAMPLE                  0x809D

/* glGet */
#define GL_MAJOR_VERSION                0x821B
#define GL_MINOR_VERSION                0x821C
#define GL_CURRENT_PROGRAM              0x8B8D

/* Map buffer */
#define GL_READ_ONLY                    0x88B8
#define GL_WRITE_ONLY                   0x88B9
#define GL_READ_WRITE                   0x88BA

/* Vertex attrib */
#define GL_VERTEX_ATTRIB_ARRAY_ENABLED  0x8622

/* ========== GLAD version info ========== */
#define GLAD_VERSION_MAJOR 0
#define GLAD_VERSION_MINOR 1

/* ========== Function declarations ========== */

/* GL 1.0 / 1.1 */
typedef void   (KHRONOS_APIENTRY *PFNGLCLEARPROC)(GLbitfield mask);
typedef void   (KHRONOS_APIENTRY *PFNGLCLEARCOLORPROC)(GLfloat r, GLfloat g, GLfloat b, GLfloat a);
typedef void   (KHRONOS_APIENTRY *PFNGLCLEARDEPTHPROC)(GLdouble depth);
typedef void   (KHRONOS_APIENTRY *PFNGLVIEWPORTPROC)(GLint x, GLint y, GLsizei w, GLsizei h);
typedef void   (KHRONOS_APIENTRY *PFNGLSCISSORPROC)(GLint x, GLint y, GLsizei w, GLsizei h);
typedef void   (KHRONOS_APIENTRY *PFNGLENABLEPROC)(GLenum cap);
typedef void   (KHRONOS_APIENTRY *PFNGLDISABLEPROC)(GLenum cap);
typedef void   (KHRONOS_APIENTRY *PFNGLDRAWARRAYSPROC)(GLenum mode, GLint first, GLsizei count);
typedef void   (KHRONOS_APIENTRY *PFNGLDRAWELEMENTSPROC)(GLenum mode, GLsizei count, GLenum type, const void* indices);
typedef const GLubyte* (KHRONOS_APIENTRY *PFNGLGETSTRINGPROC)(GLenum name);
typedef void   (KHRONOS_APIENTRY *PFNGLPIXELSTOREIPROC)(GLenum pname, GLint param);
typedef GLenum (KHRONOS_APIENTRY *PFNGLGETERRORPROC)(void);
typedef void   (KHRONOS_APIENTRY *PFNGLGETINTEGERVPROC)(GLenum pname, GLint* data);
typedef void   (KHRONOS_APIENTRY *PFNGLGETFLOATVPROC)(GLenum pname, GLfloat* data);
typedef void   (KHRONOS_APIENTRY *PFNGLGETBOOLEANVPROC)(GLenum pname, GLboolean* data);
typedef void   (KHRONOS_APIENTRY *PFNGLDEPTHMASKPROC)(GLboolean flag);
typedef void   (KHRONOS_APIENTRY *PFNGLDEPTHFUNCPROC)(GLenum func);
typedef void   (KHRONOS_APIENTRY *PFNGLBLENDFUNCPROC)(GLenum sfactor, GLenum dfactor);
typedef void   (KHRONOS_APIENTRY *PFNGLBLENDEQUATIONPROC)(GLenum mode);
typedef void   (KHRONOS_APIENTRY *PFNGLCULLFACEPROC)(GLenum mode);
typedef void   (KHRONOS_APIENTRY *PFNGLFRONTFACEPROC)(GLenum mode);
typedef void   (KHRONOS_APIENTRY *PFNGLPOLYGONMODEPROC)(GLenum face, GLenum mode);
typedef void   (KHRONOS_APIENTRY *PFNGLLINEWIDTHPROC)(GLfloat width);
typedef void   (KHRONOS_APIENTRY *PFNGLCOLORMASKPROC)(GLboolean r, GLboolean g, GLboolean b, GLboolean a);
typedef void   (KHRONOS_APIENTRY *PFNGLREADPIXELSPROC)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels);
typedef void   (KHRONOS_APIENTRY *PFNGLFLUSHPROC)(void);
typedef void   (KHRONOS_APIENTRY *PFNGLFINISHPROC)(void);
typedef void   (KHRONOS_APIENTRY *PFNGLPOINTSIZEPROC)(GLfloat size);
typedef GLboolean (KHRONOS_APIENTRY *PFNGLISENABLEDPROC)(GLenum cap);
typedef void   (KHRONOS_APIENTRY *PFNGLGENTEXTURESPROC)(GLsizei n, GLuint* textures);
typedef void   (KHRONOS_APIENTRY *PFNGLDELETETEXTURESPROC)(GLsizei n, const GLuint* textures);
typedef void   (KHRONOS_APIENTRY *PFNGLBINDTEXTUREPROC)(GLenum target, GLuint texture);
typedef void   (KHRONOS_APIENTRY *PFNGLTEXIMAGE2DPROC)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void* pixels);
typedef void   (KHRONOS_APIENTRY *PFNGLTEXSUBIMAGE2DPROC)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels);
typedef void   (KHRONOS_APIENTRY *PFNGLTEXPARAMETERIPROC)(GLenum target, GLenum pname, GLint param);
typedef void   (KHRONOS_APIENTRY *PFNGLTEXPARAMETERFPROC)(GLenum target, GLenum pname, GLfloat param);
typedef void   (KHRONOS_APIENTRY *PFNGLTEXPARAMETERIVPROC)(GLenum target, GLenum pname, const GLint* params);
typedef void   (KHRONOS_APIENTRY *PFNGLTEXPARAMETERFVPROC)(GLenum target, GLenum pname, const GLfloat* params);
typedef void   (KHRONOS_APIENTRY *PFNGLTEXIMAGE1DPROC)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void* pixels);
typedef void   (KHRONOS_APIENTRY *PFNGLGENERATEMIPMAPPROC)(GLenum target);

/* Active texture (GL 1.3+) */
typedef void   (KHRONOS_APIENTRY *PFNGLACTIVETEXTUREPROC)(GLenum texture);

/* Shaders */
typedef GLuint (KHRONOS_APIENTRY *PFNGLCREATESHADERPROC)(GLenum type);
typedef void   (KHRONOS_APIENTRY *PFNGLDELETESHADERPROC)(GLuint shader);
typedef void   (KHRONOS_APIENTRY *PFNGLSHADERSOURCEPROC)(GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length);
typedef void   (KHRONOS_APIENTRY *PFNGLCOMPILESHADERPROC)(GLuint shader);
typedef void   (KHRONOS_APIENTRY *PFNGLGETSHADERIVPROC)(GLuint shader, GLenum pname, GLint* params);
typedef void   (KHRONOS_APIENTRY *PFNGLGETSHADERINFOLOGPROC)(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog);

/* Programs */
typedef GLuint (KHRONOS_APIENTRY *PFNGLCREATEPROGRAMPROC)(void);
typedef void   (KHRONOS_APIENTRY *PFNGLDELETEPROGRAMPROC)(GLuint program);
typedef void   (KHRONOS_APIENTRY *PFNGLATTACHSHADERPROC)(GLuint program, GLuint shader);
typedef void   (KHRONOS_APIENTRY *PFNGLLINKPROGRAMPROC)(GLuint program);
typedef void   (KHRONOS_APIENTRY *PFNGLUSEPROGRAMPROC)(GLuint program);
typedef void   (KHRONOS_APIENTRY *PFNGLGETPROGRAMIVPROC)(GLuint program, GLenum pname, GLint* params);
typedef void   (KHRONOS_APIENTRY *PFNGLGETPROGRAMINFOLOGPROC)(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
typedef GLint  (KHRONOS_APIENTRY *PFNGLGETUNIFORMLOCATIONPROC)(GLuint program, const GLchar* name);
typedef GLint  (KHRONOS_APIENTRY *PFNGLGETATTRIBLOCATIONPROC)(GLuint program, const GLchar* name);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM1IPROC)(GLint location, GLint v0);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM1FPROC)(GLint location, GLfloat v0);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM2FPROC)(GLint location, GLfloat v0, GLfloat v1);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM3FPROC)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM4FPROC)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM2IPROC)(GLint location, GLint v0, GLint v1);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM3IPROC)(GLint location, GLint v0, GLint v1, GLint v2);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM4IPROC)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM1FVPROC)(GLint location, GLsizei count, const GLfloat* value);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM2FVPROC)(GLint location, GLsizei count, const GLfloat* value);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM3FVPROC)(GLint location, GLsizei count, const GLfloat* value);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM4FVPROC)(GLint location, GLsizei count, const GLfloat* value);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORM1IVPROC)(GLint location, GLsizei count, const GLint* value);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORMMATRIX2FVPROC)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORMMATRIX3FVPROC)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORMMATRIX4FVPROC)(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
typedef void   (KHRONOS_APIENTRY *PFNGLVALIDATEPROGRAMPROC)(GLuint program);
typedef void   (KHRONOS_APIENTRY *PFNGLDETACHSHADERPROC)(GLuint program, GLuint shader);
typedef void   (KHRONOS_APIENTRY *PFNGLBINDATTRIBLOCATIONPROC)(GLuint program, GLuint index, const GLchar* name);
typedef void   (KHRONOS_APIENTRY *PFNGLGETACTIVEUNIFORMPROC)(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
typedef void   (KHRONOS_APIENTRY *PFNGLGETACTIVEATTRIBPROC)(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);

/* Framebuffer objects */
typedef void   (KHRONOS_APIENTRY *PFNGLGENFRAMEBUFFERSPROC)(GLsizei n, GLuint* framebuffers);
typedef void   (KHRONOS_APIENTRY *PFNGLDELETEFRAMEBUFFERSPROC)(GLsizei n, const GLuint* framebuffers);
typedef void   (KHRONOS_APIENTRY *PFNGLBINDFRAMEBUFFERPROC)(GLenum target, GLuint framebuffer);
typedef void   (KHRONOS_APIENTRY *PFNGLFRAMEBUFFERTEXTURE2DPROC)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
typedef GLenum (KHRONOS_APIENTRY *PFNGLCHECKFRAMEBUFFERSTATUSPROC)(GLenum target);
typedef void   (KHRONOS_APIENTRY *PFNGLGENRENDERBUFFERSPROC)(GLsizei n, GLuint* renderbuffers);
typedef void   (KHRONOS_APIENTRY *PFNGLDELETERENDERBUFFERSPROC)(GLsizei n, const GLuint* renderbuffers);
typedef void   (KHRONOS_APIENTRY *PFNGLBINDRENDERBUFFERPROC)(GLenum target, GLuint renderbuffer);
typedef void   (KHRONOS_APIENTRY *PFNGLRENDERBUFFERSTORAGEPROC)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
typedef void   (KHRONOS_APIENTRY *PFNGLFRAMEBUFFERRENDERBUFFERPROC)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
typedef void   (KHRONOS_APIENTRY *PFNGLBLITFRAMEBUFFERPROC)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
typedef void   (KHRONOS_APIENTRY *PFNGLDRAWBUFFERSPROC)(GLsizei n, const GLenum* bufs);
typedef void   (KHRONOS_APIENTRY *PFNGLREADBUFFERPROC)(GLenum src);

/* Buffer mapping */
typedef void*  (KHRONOS_APIENTRY *PFNGLMAPBUFFERRANGEPROC)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
typedef GLboolean (KHRONOS_APIENTRY *PFNGLUNMAPBUFFERPROC)(GLenum target);
typedef void   (KHRONOS_APIENTRY *PFNGLBUFFERSUBDATAPROC)(GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
typedef void   (KHRONOS_APIENTRY *PFNGLCOPYBUFFERSUBDATAPROC)(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);

/* Uniform buffer objects */
typedef void   (KHRONOS_APIENTRY *PFNGLBINDBUFFERBASEPROC)(GLenum target, GLuint index, GLuint buffer);
typedef void   (KHRONOS_APIENTRY *PFNGLBINDBUFFERRANGEPROC)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
typedef GLuint (KHRONOS_APIENTRY *PFNGLGETUNIFORMBLOCKINDEXPROC)(GLuint program, const GLchar* uniformBlockName);
typedef void   (KHRONOS_APIENTRY *PFNGLUNIFORMBLOCKBINDINGPROC)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);

/* Vertex attrib extras */
typedef void   (KHRONOS_APIENTRY *PFNGLDISABLEVERTEXATTRIBARRAYPROC)(GLuint index);
typedef void   (KHRONOS_APIENTRY *PFNGLVERTEXATTRIBIPOINTERPROC)(GLuint index, GLint size, GLenum type, GLsizei stride, const void* pointer);
typedef void   (KHRONOS_APIENTRY *PFNGLVERTEXATTRIBDIVISORPROC)(GLuint index, GLuint divisor);

/* Instanced drawing */
typedef void   (KHRONOS_APIENTRY *PFNGLDRAWARRAYSINSTANCEDPROC)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
typedef void   (KHRONOS_APIENTRY *PFNGLDRAWELEMENTSINSTANCEDPROC)(GLenum mode, GLsizei count, GLenum type, const void* indices, GLsizei instancecount);

/* Query */
typedef void   (KHRONOS_APIENTRY *PFNGLGENQUERIESPROC)(GLsizei n, GLuint* ids);
typedef void   (KHRONOS_APIENTRY *PFNGLDELETEQUERIESPROC)(GLsizei n, const GLuint* ids);
typedef void   (KHRONOS_APIENTRY *PFNGLBEGINQUERYPROC)(GLenum target, GLuint id);
typedef void   (KHRONOS_APIENTRY *PFNGLENDQUERYPROC)(GLenum target);
typedef void   (KHRONOS_APIENTRY *PFNGLGETQUERYOBJECTUIVPROC)(GLuint id, GLenum pname, GLuint* params);
typedef void   (KHRONOS_APIENTRY *PFNGLGETQUERYOBJECTIVPROC)(GLuint id, GLenum pname, GLint* params);

/* GetStringi (GL 3.0) */
typedef const GLubyte* (KHRONOS_APIENTRY *PFNGLGETSTRINGIPROC)(GLenum name, GLuint index);

/* Sampler objects (GL 3.3) */
typedef void   (KHRONOS_APIENTRY *PFNGLGENSAMPLERSPROC)(GLsizei count, GLuint* samplers);
typedef void   (KHRONOS_APIENTRY *PFNGLDELETESAMPLERSPROC)(GLsizei count, const GLuint* samplers);
typedef void   (KHRONOS_APIENTRY *PFNGLBINDSAMPLERPROC)(GLuint unit, GLuint sampler);
typedef void   (KHRONOS_APIENTRY *PFNGLSAMPLERPARAMETERIPROC)(GLuint sampler, GLenum pname, GLint param);
typedef void   (KHRONOS_APIENTRY *PFNGLSAMPLERPARAMETERFPROC)(GLuint sampler, GLenum pname, GLfloat param);

/* VAO */
typedef void   (KHRONOS_APIENTRY *PFNGLGENVERTEXARRAYSPROC)(GLsizei n, GLuint* arrays);
typedef void   (KHRONOS_APIENTRY *PFNGLDELETEVERTEXARRAYSPROC)(GLsizei n, const GLuint* arrays);
typedef void   (KHRONOS_APIENTRY *PFNGLBINDVERTEXARRAYPROC)(GLuint array);

/* VBO */
typedef void   (KHRONOS_APIENTRY *PFNGLGENBUFFERSPROC)(GLsizei n, GLuint* buffers);
typedef void   (KHRONOS_APIENTRY *PFNGLDELETEBUFFERSPROC)(GLsizei n, const GLuint* buffers);
typedef void   (KHRONOS_APIENTRY *PFNGLBINDBUFFERPROC)(GLenum target, GLuint buffer);
typedef void   (KHRONOS_APIENTRY *PFNGLBUFFERDATAPROC)(GLenum target, GLsizeiptr size, const void* data, GLenum usage);
typedef void   (KHRONOS_APIENTRY *PFNGLVERTEXATTRIBPOINTERPROC)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* pointer);
typedef void   (KHRONOS_APIENTRY *PFNGLENABLEVERTEXATTRIBARRAYPROC)(GLuint index);

/* ========== Global function pointers ========== */

/* GL 1.0 / 1.1 core */
extern PFNGLCLEARPROC                  glClear;
extern PFNGLCLEARCOLORPROC             glClearColor;
extern PFNGLCLEARDEPTHPROC             glClearDepth;
extern PFNGLVIEWPORTPROC               glViewport;
extern PFNGLSCISSORPROC                glScissor;
extern PFNGLENABLEPROC                 glEnable;
extern PFNGLDISABLEPROC                glDisable;
extern PFNGLDRAWARRAYSPROC             glDrawArrays;
extern PFNGLDRAWELEMENTSPROC           glDrawElements;
extern PFNGLGETSTRINGPROC              glGetString;
extern PFNGLPIXELSTOREIPROC            glPixelStorei;
extern PFNGLGETERRORPROC               glGetError;
extern PFNGLGETINTEGERVPROC            glGetIntegerv;
extern PFNGLGETFLOATVPROC              glGetFloatv;
extern PFNGLGETBOOLEANVPROC            glGetBooleanv;
extern PFNGLDEPTHMASKPROC              glDepthMask;
extern PFNGLDEPTHFUNCPROC              glDepthFunc;
extern PFNGLBLENDFUNCPROC              glBlendFunc;
extern PFNGLBLENDEQUATIONPROC          glBlendEquation;
extern PFNGLCULLFACEPROC               glCullFace;
extern PFNGLFRONTFACEPROC              glFrontFace;
extern PFNGLPOLYGONMODEPROC            glPolygonMode;
extern PFNGLLINEWIDTHPROC              glLineWidth;
extern PFNGLCOLORMASKPROC              glColorMask;
extern PFNGLREADPIXELSPROC             glReadPixels;
extern PFNGLFLUSHPROC                  glFlush;
extern PFNGLFINISHPROC                 glFinish;
extern PFNGLPOINTSIZEPROC              glPointSize;
extern PFNGLISENABLEDPROC              glIsEnabled;

/* Textures */
extern PFNGLGENTEXTURESPROC            glGenTextures;
extern PFNGLDELETETEXTURESPROC         glDeleteTextures;
extern PFNGLBINDTEXTUREPROC            glBindTexture;
extern PFNGLTEXIMAGE2DPROC             glTexImage2D;
extern PFNGLTEXSUBIMAGE2DPROC          glTexSubImage2D;
extern PFNGLTEXPARAMETERIPROC          glTexParameteri;
extern PFNGLTEXPARAMETERFPROC          glTexParameterf;
extern PFNGLTEXPARAMETERIVPROC         glTexParameteriv;
extern PFNGLTEXPARAMETERFVPROC         glTexParameterfv;
extern PFNGLTEXIMAGE1DPROC             glTexImage1D;
extern PFNGLGENERATEMIPMAPPROC         glGenerateMipmap;
extern PFNGLACTIVETEXTUREPROC          glActiveTexture;

/* Shaders */
extern PFNGLCREATESHADERPROC           glCreateShader;
extern PFNGLDELETESHADERPROC           glDeleteShader;
extern PFNGLSHADERSOURCEPROC           glShaderSource;
extern PFNGLCOMPILESHADERPROC          glCompileShader;
extern PFNGLGETSHADERIVPROC            glGetShaderiv;
extern PFNGLGETSHADERINFOLOGPROC       glGetShaderInfoLog;

/* Programs */
extern PFNGLCREATEPROGRAMPROC          glCreateProgram;
extern PFNGLDELETEPROGRAMPROC          glDeleteProgram;
extern PFNGLATTACHSHADERPROC           glAttachShader;
extern PFNGLDETACHSHADERPROC           glDetachShader;
extern PFNGLLINKPROGRAMPROC            glLinkProgram;
extern PFNGLUSEPROGRAMPROC             glUseProgram;
extern PFNGLVALIDATEPROGRAMPROC        glValidateProgram;
extern PFNGLGETPROGRAMIVPROC           glGetProgramiv;
extern PFNGLGETPROGRAMINFOLOGPROC      glGetProgramInfoLog;
extern PFNGLGETUNIFORMLOCATIONPROC     glGetUniformLocation;
extern PFNGLGETATTRIBLOCATIONPROC      glGetAttribLocation;
extern PFNGLBINDATTRIBLOCATIONPROC     glBindAttribLocation;
extern PFNGLGETACTIVEUNIFORMPROC       glGetActiveUniform;
extern PFNGLGETACTIVEATTRIBPROC        glGetActiveAttrib;

/* Uniforms */
extern PFNGLUNIFORM1IPROC              glUniform1i;
extern PFNGLUNIFORM1FPROC              glUniform1f;
extern PFNGLUNIFORM2FPROC              glUniform2f;
extern PFNGLUNIFORM3FPROC              glUniform3f;
extern PFNGLUNIFORM4FPROC              glUniform4f;
extern PFNGLUNIFORM2IPROC              glUniform2i;
extern PFNGLUNIFORM3IPROC              glUniform3i;
extern PFNGLUNIFORM4IPROC              glUniform4i;
extern PFNGLUNIFORM1FVPROC             glUniform1fv;
extern PFNGLUNIFORM2FVPROC             glUniform2fv;
extern PFNGLUNIFORM3FVPROC             glUniform3fv;
extern PFNGLUNIFORM4FVPROC             glUniform4fv;
extern PFNGLUNIFORM1IVPROC             glUniform1iv;
extern PFNGLUNIFORMMATRIX2FVPROC       glUniformMatrix2fv;
extern PFNGLUNIFORMMATRIX3FVPROC       glUniformMatrix3fv;
extern PFNGLUNIFORMMATRIX4FVPROC       glUniformMatrix4fv;

/* VAO */
extern PFNGLGENVERTEXARRAYSPROC        glGenVertexArrays;
extern PFNGLDELETEVERTEXARRAYSPROC     glDeleteVertexArrays;
extern PFNGLBINDVERTEXARRAYPROC        glBindVertexArray;

/* VBO */
extern PFNGLGENBUFFERSPROC             glGenBuffers;
extern PFNGLDELETEBUFFERSPROC          glDeleteBuffers;
extern PFNGLBINDBUFFERPROC             glBindBuffer;
extern PFNGLBUFFERDATAPROC             glBufferData;
extern PFNGLBUFFERSUBDATAPROC          glBufferSubData;
extern PFNGLCOPYBUFFERSUBDATAPROC      glCopyBufferSubData;
extern PFNGLVERTEXATTRIBPOINTERPROC    glVertexAttribPointer;
extern PFNGLVERTEXATTRIBIPOINTERPROC   glVertexAttribIPointer;
extern PFNGLENABLEVERTEXATTRIBARRAYPROC  glEnableVertexAttribArray;
extern PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
extern PFNGLVERTEXATTRIBDIVISORPROC    glVertexAttribDivisor;

/* Framebuffer */
extern PFNGLGENFRAMEBUFFERSPROC        glGenFramebuffers;
extern PFNGLDELETEFRAMEBUFFERSPROC     glDeleteFramebuffers;
extern PFNGLBINDFRAMEBUFFERPROC        glBindFramebuffer;
extern PFNGLFRAMEBUFFERTEXTURE2DPROC   glFramebufferTexture2D;
extern PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
extern PFNGLGENRENDERBUFFERSPROC       glGenRenderbuffers;
extern PFNGLDELETERENDERBUFFERSPROC    glDeleteRenderbuffers;
extern PFNGLBINDRENDERBUFFERPROC       glBindRenderbuffer;
extern PFNGLRENDERBUFFERSTORAGEPROC    glRenderbufferStorage;
extern PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
extern PFNGLBLITFRAMEBUFFERPROC        glBlitFramebuffer;
extern PFNGLDRAWBUFFERSPROC            glDrawBuffers;
extern PFNGLREADBUFFERPROC             glReadBuffer;

/* Buffer mapping */
extern PFNGLMAPBUFFERRANGEPROC         glMapBufferRange;
extern PFNGLUNMAPBUFFERPROC            glUnmapBuffer;

/* Uniform buffer */
extern PFNGLBINDBUFFERBASEPROC         glBindBufferBase;
extern PFNGLBINDBUFFERRANGEPROC        glBindBufferRange;
extern PFNGLGETUNIFORMBLOCKINDEXPROC   glGetUniformBlockIndex;
extern PFNGLUNIFORMBLOCKBINDINGPROC    glUniformBlockBinding;

/* Instanced drawing */
extern PFNGLDRAWARRAYSINSTANCEDPROC    glDrawArraysInstanced;
extern PFNGLDRAWELEMENTSINSTANCEDPROC  glDrawElementsInstanced;

/* Query */
extern PFNGLGENQUERIESPROC             glGenQueries;
extern PFNGLDELETEQUERIESPROC          glDeleteQueries;
extern PFNGLBEGINQUERYPROC             glBeginQuery;
extern PFNGLENDQUERYPROC               glEndQuery;
extern PFNGLGETQUERYOBJECTUIVPROC      glGetQueryObjectuiv;
extern PFNGLGETQUERYOBJECTIVPROC       glGetQueryObjectiv;

/* GL 3.0+ */
extern PFNGLGETSTRINGIPROC             glGetStringi;

/* Sampler objects (GL 3.3) */
extern PFNGLGENSAMPLERSPROC            glGenSamplers;
extern PFNGLDELETESAMPLERSPROC         glDeleteSamplers;
extern PFNGLBINDSAMPLERPROC            glBindSampler;
extern PFNGLSAMPLERPARAMETERIPROC      glSamplerParameteri;
extern PFNGLSAMPLERPARAMETERFPROC      glSamplerParameterf;

/* ========== Loader ========== */

/* Load OpenGL functions using the provided loader function.
 * Returns 1 on success, 0 on failure.
 * Usage: gladLoadGLLoader((GLADloadproc)glfwGetProcAddress) */
int gladLoadGLLoader(GLADloadproc load);

#ifdef __cplusplus
}
#endif

#endif /* GLAD_H_ */
