/*
 * GLAD - OpenGL Loader Generated by glad 0.1.36
 *
 * Language/Generator: C/C++
 * Specification: gl
 * APIs: gl=3.3
 * Profile: core
 * Loader: True
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <glad/glad.h>

/* ========== Function pointer definitions ========== */

/* GL 1.0 / 1.1 core */
PFNGLCLEARPROC                  glClear = NULL;
PFNGLCLEARCOLORPROC             glClearColor = NULL;
PFNGLCLEARDEPTHPROC             glClearDepth = NULL;
PFNGLVIEWPORTPROC               glViewport = NULL;
PFNGLSCISSORPROC                glScissor = NULL;
PFNGLENABLEPROC                 glEnable = NULL;
PFNGLDISABLEPROC                glDisable = NULL;
PFNGLDRAWARRAYSPROC             glDrawArrays = NULL;
PFNGLDRAWELEMENTSPROC           glDrawElements = NULL;
PFNGLGETSTRINGPROC              glGetString = NULL;
PFNGLPIXELSTOREIPROC            glPixelStorei = NULL;
PFNGLGETERRORPROC               glGetError = NULL;
PFNGLGETINTEGERVPROC            glGetIntegerv = NULL;
PFNGLGETFLOATVPROC              glGetFloatv = NULL;
PFNGLGETBOOLEANVPROC            glGetBooleanv = NULL;
PFNGLDEPTHMASKPROC              glDepthMask = NULL;
PFNGLDEPTHFUNCPROC              glDepthFunc = NULL;
PFNGLBLENDFUNCPROC              glBlendFunc = NULL;
PFNGLBLENDEQUATIONPROC          glBlendEquation = NULL;
PFNGLCULLFACEPROC               glCullFace = NULL;
PFNGLFRONTFACEPROC              glFrontFace = NULL;
PFNGLPOLYGONMODEPROC            glPolygonMode = NULL;
PFNGLLINEWIDTHPROC              glLineWidth = NULL;
PFNGLCOLORMASKPROC              glColorMask = NULL;
PFNGLREADPIXELSPROC             glReadPixels = NULL;
PFNGLFLUSHPROC                  glFlush = NULL;
PFNGLFINISHPROC                 glFinish = NULL;
PFNGLPOINTSIZEPROC              glPointSize = NULL;
PFNGLISENABLEDPROC              glIsEnabled = NULL;

/* Textures */
PFNGLGENTEXTURESPROC            glGenTextures = NULL;
PFNGLDELETETEXTURESPROC         glDeleteTextures = NULL;
PFNGLBINDTEXTUREPROC            glBindTexture = NULL;
PFNGLTEXIMAGE2DPROC             glTexImage2D = NULL;
PFNGLTEXSUBIMAGE2DPROC          glTexSubImage2D = NULL;
PFNGLTEXPARAMETERIPROC          glTexParameteri = NULL;
PFNGLTEXPARAMETERFPROC          glTexParameterf = NULL;
PFNGLTEXPARAMETERIVPROC         glTexParameteriv = NULL;
PFNGLTEXPARAMETERFVPROC         glTexParameterfv = NULL;
PFNGLTEXIMAGE1DPROC             glTexImage1D = NULL;
PFNGLGENERATEMIPMAPPROC         glGenerateMipmap = NULL;
PFNGLACTIVETEXTUREPROC          glActiveTexture = NULL;

/* Shaders */
PFNGLCREATESHADERPROC           glCreateShader = NULL;
PFNGLDELETESHADERPROC           glDeleteShader = NULL;
PFNGLSHADERSOURCEPROC           glShaderSource = NULL;
PFNGLCOMPILESHADERPROC          glCompileShader = NULL;
PFNGLGETSHADERIVPROC            glGetShaderiv = NULL;
PFNGLGETSHADERINFOLOGPROC       glGetShaderInfoLog = NULL;

/* Programs */
PFNGLCREATEPROGRAMPROC          glCreateProgram = NULL;
PFNGLDELETEPROGRAMPROC          glDeleteProgram = NULL;
PFNGLATTACHSHADERPROC           glAttachShader = NULL;
PFNGLDETACHSHADERPROC           glDetachShader = NULL;
PFNGLLINKPROGRAMPROC            glLinkProgram = NULL;
PFNGLUSEPROGRAMPROC             glUseProgram = NULL;
PFNGLVALIDATEPROGRAMPROC        glValidateProgram = NULL;
PFNGLGETPROGRAMIVPROC           glGetProgramiv = NULL;
PFNGLGETPROGRAMINFOLOGPROC      glGetProgramInfoLog = NULL;
PFNGLGETUNIFORMLOCATIONPROC     glGetUniformLocation = NULL;
PFNGLGETATTRIBLOCATIONPROC      glGetAttribLocation = NULL;
PFNGLBINDATTRIBLOCATIONPROC     glBindAttribLocation = NULL;
PFNGLGETACTIVEUNIFORMPROC       glGetActiveUniform = NULL;
PFNGLGETACTIVEATTRIBPROC        glGetActiveAttrib = NULL;

/* Uniforms */
PFNGLUNIFORM1IPROC              glUniform1i = NULL;
PFNGLUNIFORM1FPROC              glUniform1f = NULL;
PFNGLUNIFORM2FPROC              glUniform2f = NULL;
PFNGLUNIFORM3FPROC              glUniform3f = NULL;
PFNGLUNIFORM4FPROC              glUniform4f = NULL;
PFNGLUNIFORM2IPROC              glUniform2i = NULL;
PFNGLUNIFORM3IPROC              glUniform3i = NULL;
PFNGLUNIFORM4IPROC              glUniform4i = NULL;
PFNGLUNIFORM1FVPROC             glUniform1fv = NULL;
PFNGLUNIFORM2FVPROC             glUniform2fv = NULL;
PFNGLUNIFORM3FVPROC             glUniform3fv = NULL;
PFNGLUNIFORM4FVPROC             glUniform4fv = NULL;
PFNGLUNIFORM1IVPROC             glUniform1iv = NULL;
PFNGLUNIFORMMATRIX2FVPROC       glUniformMatrix2fv = NULL;
PFNGLUNIFORMMATRIX3FVPROC       glUniformMatrix3fv = NULL;
PFNGLUNIFORMMATRIX4FVPROC       glUniformMatrix4fv = NULL;

/* VAO */
PFNGLGENVERTEXARRAYSPROC        glGenVertexArrays = NULL;
PFNGLDELETEVERTEXARRAYSPROC     glDeleteVertexArrays = NULL;
PFNGLBINDVERTEXARRAYPROC        glBindVertexArray = NULL;

/* VBO */
PFNGLGENBUFFERSPROC             glGenBuffers = NULL;
PFNGLDELETEBUFFERSPROC          glDeleteBuffers = NULL;
PFNGLBINDBUFFERPROC             glBindBuffer = NULL;
PFNGLBUFFERDATAPROC             glBufferData = NULL;
PFNGLBUFFERSUBDATAPROC          glBufferSubData = NULL;
PFNGLCOPYBUFFERSUBDATAPROC      glCopyBufferSubData = NULL;
PFNGLVERTEXATTRIBPOINTERPROC    glVertexAttribPointer = NULL;
PFNGLVERTEXATTRIBIPOINTERPROC   glVertexAttribIPointer = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC  glEnableVertexAttribArray = NULL;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = NULL;
PFNGLVERTEXATTRIBDIVISORPROC    glVertexAttribDivisor = NULL;

/* Framebuffer */
PFNGLGENFRAMEBUFFERSPROC        glGenFramebuffers = NULL;
PFNGLDELETEFRAMEBUFFERSPROC     glDeleteFramebuffers = NULL;
PFNGLBINDFRAMEBUFFERPROC        glBindFramebuffer = NULL;
PFNGLFRAMEBUFFERTEXTURE2DPROC   glFramebufferTexture2D = NULL;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus = NULL;
PFNGLGENRENDERBUFFERSPROC       glGenRenderbuffers = NULL;
PFNGLDELETERENDERBUFFERSPROC    glDeleteRenderbuffers = NULL;
PFNGLBINDRENDERBUFFERPROC       glBindRenderbuffer = NULL;
PFNGLRENDERBUFFERSTORAGEPROC    glRenderbufferStorage = NULL;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer = NULL;
PFNGLBLITFRAMEBUFFERPROC        glBlitFramebuffer = NULL;
PFNGLDRAWBUFFERSPROC            glDrawBuffers = NULL;
PFNGLREADBUFFERPROC             glReadBuffer = NULL;

/* Buffer mapping */
PFNGLMAPBUFFERRANGEPROC         glMapBufferRange = NULL;
PFNGLUNMAPBUFFERPROC            glUnmapBuffer = NULL;

/* Uniform buffer */
PFNGLBINDBUFFERBASEPROC         glBindBufferBase = NULL;
PFNGLBINDBUFFERRANGEPROC        glBindBufferRange = NULL;
PFNGLGETUNIFORMBLOCKINDEXPROC   glGetUniformBlockIndex = NULL;
PFNGLUNIFORMBLOCKBINDINGPROC    glUniformBlockBinding = NULL;

/* Instanced drawing */
PFNGLDRAWARRAYSINSTANCEDPROC    glDrawArraysInstanced = NULL;
PFNGLDRAWELEMENTSINSTANCEDPROC  glDrawElementsInstanced = NULL;

/* Query */
PFNGLGENQUERIESPROC             glGenQueries = NULL;
PFNGLDELETEQUERIESPROC          glDeleteQueries = NULL;
PFNGLBEGINQUERYPROC             glBeginQuery = NULL;
PFNGLENDQUERYPROC               glEndQuery = NULL;
PFNGLGETQUERYOBJECTUIVPROC      glGetQueryObjectuiv = NULL;
PFNGLGETQUERYOBJECTIVPROC       glGetQueryObjectiv = NULL;

/* GL 3.0+ */
PFNGLGETSTRINGIPROC             glGetStringi = NULL;

/* Sampler objects (GL 3.3) */
PFNGLGENSAMPLERSPROC            glGenSamplers = NULL;
PFNGLDELETESAMPLERSPROC         glDeleteSamplers = NULL;
PFNGLBINDSAMPLERPROC            glBindSampler = NULL;
PFNGLSAMPLERPARAMETERIPROC      glSamplerParameteri = NULL;
PFNGLSAMPLERPARAMETERFPROC      glSamplerParameterf = NULL;

/* ========== Loader implementation ========== */

static void glad_load_gl10(GLADloadproc load) {
    glClear = (PFNGLCLEARPROC)load("glClear");
    glClearColor = (PFNGLCLEARCOLORPROC)load("glClearColor");
    glClearDepth = (PFNGLCLEARDEPTHPROC)load("glClearDepth");
    glViewport = (PFNGLVIEWPORTPROC)load("glViewport");
    glScissor = (PFNGLSCISSORPROC)load("glScissor");
    glEnable = (PFNGLENABLEPROC)load("glEnable");
    glDisable = (PFNGLDISABLEPROC)load("glDisable");
    glGetString = (PFNGLGETSTRINGPROC)load("glGetString");
    glPixelStorei = (PFNGLPIXELSTOREIPROC)load("glPixelStorei");
    glGetError = (PFNGLGETERRORPROC)load("glGetError");
    glGetIntegerv = (PFNGLGETINTEGERVPROC)load("glGetIntegerv");
    glGetFloatv = (PFNGLGETFLOATVPROC)load("glGetFloatv");
    glGetBooleanv = (PFNGLGETBOOLEANVPROC)load("glGetBooleanv");
    glDepthMask = (PFNGLDEPTHMASKPROC)load("glDepthMask");
    glDepthFunc = (PFNGLDEPTHFUNCPROC)load("glDepthFunc");
    glBlendFunc = (PFNGLBLENDFUNCPROC)load("glBlendFunc");
    glCullFace = (PFNGLCULLFACEPROC)load("glCullFace");
    glFrontFace = (PFNGLFRONTFACEPROC)load("glFrontFace");
    glPolygonMode = (PFNGLPOLYGONMODEPROC)load("glPolygonMode");
    glLineWidth = (PFNGLLINEWIDTHPROC)load("glLineWidth");
    glColorMask = (PFNGLCOLORMASKPROC)load("glColorMask");
    glReadPixels = (PFNGLREADPIXELSPROC)load("glReadPixels");
    glFlush = (PFNGLFLUSHPROC)load("glFlush");
    glFinish = (PFNGLFINISHPROC)load("glFinish");
    glPointSize = (PFNGLPOINTSIZEPROC)load("glPointSize");
    glIsEnabled = (PFNGLISENABLEDPROC)load("glIsEnabled");
    glTexImage1D = (PFNGLTEXIMAGE1DPROC)load("glTexImage1D");
    glTexParameteri = (PFNGLTEXPARAMETERIPROC)load("glTexParameteri");
    glTexParameterf = (PFNGLTEXPARAMETERFPROC)load("glTexParameterf");
    glTexParameteriv = (PFNGLTEXPARAMETERIVPROC)load("glTexParameteriv");
    glTexParameterfv = (PFNGLTEXPARAMETERFVPROC)load("glTexParameterfv");
}

static void glad_load_gl11(GLADloadproc load) {
    glDrawArrays = (PFNGLDRAWARRAYSPROC)load("glDrawArrays");
    glDrawElements = (PFNGLDRAWELEMENTSPROC)load("glDrawElements");
    glGenTextures = (PFNGLGENTEXTURESPROC)load("glGenTextures");
    glDeleteTextures = (PFNGLDELETETEXTURESPROC)load("glDeleteTextures");
    glBindTexture = (PFNGLBINDTEXTUREPROC)load("glBindTexture");
    glTexImage2D = (PFNGLTEXIMAGE2DPROC)load("glTexImage2D");
    glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC)load("glTexSubImage2D");
}

static void glad_load_gl13(GLADloadproc load) {
    glActiveTexture = (PFNGLACTIVETEXTUREPROC)load("glActiveTexture");
}

static void glad_load_gl14(GLADloadproc load) {
    glBlendEquation = (PFNGLBLENDEQUATIONPROC)load("glBlendEquation");
}

static void glad_load_gl15(GLADloadproc load) {
    glGenBuffers = (PFNGLGENBUFFERSPROC)load("glGenBuffers");
    glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)load("glDeleteBuffers");
    glBindBuffer = (PFNGLBINDBUFFERPROC)load("glBindBuffer");
    glBufferData = (PFNGLBUFFERDATAPROC)load("glBufferData");
    glBufferSubData = (PFNGLBUFFERSUBDATAPROC)load("glBufferSubData");
    glUnmapBuffer = (PFNGLUNMAPBUFFERPROC)load("glUnmapBuffer");
    glGenQueries = (PFNGLGENQUERIESPROC)load("glGenQueries");
    glDeleteQueries = (PFNGLDELETEQUERIESPROC)load("glDeleteQueries");
    glBeginQuery = (PFNGLBEGINQUERYPROC)load("glBeginQuery");
    glEndQuery = (PFNGLENDQUERYPROC)load("glEndQuery");
    glGetQueryObjectiv = (PFNGLGETQUERYOBJECTIVPROC)load("glGetQueryObjectiv");
    glGetQueryObjectuiv = (PFNGLGETQUERYOBJECTUIVPROC)load("glGetQueryObjectuiv");
}

static void glad_load_gl20(GLADloadproc load) {
    glCreateShader = (PFNGLCREATESHADERPROC)load("glCreateShader");
    glDeleteShader = (PFNGLDELETESHADERPROC)load("glDeleteShader");
    glShaderSource = (PFNGLSHADERSOURCEPROC)load("glShaderSource");
    glCompileShader = (PFNGLCOMPILESHADERPROC)load("glCompileShader");
    glGetShaderiv = (PFNGLGETSHADERIVPROC)load("glGetShaderiv");
    glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)load("glGetShaderInfoLog");
    glCreateProgram = (PFNGLCREATEPROGRAMPROC)load("glCreateProgram");
    glDeleteProgram = (PFNGLDELETEPROGRAMPROC)load("glDeleteProgram");
    glAttachShader = (PFNGLATTACHSHADERPROC)load("glAttachShader");
    glDetachShader = (PFNGLDETACHSHADERPROC)load("glDetachShader");
    glLinkProgram = (PFNGLLINKPROGRAMPROC)load("glLinkProgram");
    glUseProgram = (PFNGLUSEPROGRAMPROC)load("glUseProgram");
    glValidateProgram = (PFNGLVALIDATEPROGRAMPROC)load("glValidateProgram");
    glGetProgramiv = (PFNGLGETPROGRAMIVPROC)load("glGetProgramiv");
    glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)load("glGetProgramInfoLog");
    glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)load("glGetUniformLocation");
    glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC)load("glGetAttribLocation");
    glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC)load("glBindAttribLocation");
    glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC)load("glGetActiveUniform");
    glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC)load("glGetActiveAttrib");
    glUniform1i = (PFNGLUNIFORM1IPROC)load("glUniform1i");
    glUniform1f = (PFNGLUNIFORM1FPROC)load("glUniform1f");
    glUniform2f = (PFNGLUNIFORM2FPROC)load("glUniform2f");
    glUniform3f = (PFNGLUNIFORM3FPROC)load("glUniform3f");
    glUniform4f = (PFNGLUNIFORM4FPROC)load("glUniform4f");
    glUniform2i = (PFNGLUNIFORM2IPROC)load("glUniform2i");
    glUniform3i = (PFNGLUNIFORM3IPROC)load("glUniform3i");
    glUniform4i = (PFNGLUNIFORM4IPROC)load("glUniform4i");
    glUniform1fv = (PFNGLUNIFORM1FVPROC)load("glUniform1fv");
    glUniform2fv = (PFNGLUNIFORM2FVPROC)load("glUniform2fv");
    glUniform3fv = (PFNGLUNIFORM3FVPROC)load("glUniform3fv");
    glUniform4fv = (PFNGLUNIFORM4FVPROC)load("glUniform4fv");
    glUniform1iv = (PFNGLUNIFORM1IVPROC)load("glUniform1iv");
    glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC)load("glUniformMatrix2fv");
    glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)load("glUniformMatrix3fv");
    glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)load("glUniformMatrix4fv");
    glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)load("glEnableVertexAttribArray");
    glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)load("glDisableVertexAttribArray");
    glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)load("glVertexAttribPointer");
}

static void glad_load_gl30(GLADloadproc load) {
    glGetStringi = (PFNGLGETSTRINGIPROC)load("glGetStringi");
    glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)load("glGenerateMipmap");
    glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)load("glGenVertexArrays");
    glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)load("glDeleteVertexArrays");
    glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)load("glBindVertexArray");
    glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC)load("glGenFramebuffers");
    glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)load("glDeleteFramebuffers");
    glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)load("glBindFramebuffer");
    glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC)load("glFramebufferTexture2D");
    glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)load("glCheckFramebufferStatus");
    glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)load("glGenRenderbuffers");
    glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)load("glDeleteRenderbuffers");
    glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)load("glBindRenderbuffer");
    glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)load("glRenderbufferStorage");
    glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)load("glFramebufferRenderbuffer");
    glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC)load("glBlitFramebuffer");
    glMapBufferRange = (PFNGLMAPBUFFERRANGEPROC)load("glMapBufferRange");
    glVertexAttribIPointer = (PFNGLVERTEXATTRIBIPOINTERPROC)load("glVertexAttribIPointer");
    glReadBuffer = (PFNGLREADBUFFERPROC)load("glReadBuffer");
    glDrawBuffers = (PFNGLDRAWBUFFERSPROC)load("glDrawBuffers");
}

static void glad_load_gl31(GLADloadproc load) {
    glCopyBufferSubData = (PFNGLCOPYBUFFERSUBDATAPROC)load("glCopyBufferSubData");
    glGetUniformBlockIndex = (PFNGLGETUNIFORMBLOCKINDEXPROC)load("glGetUniformBlockIndex");
    glUniformBlockBinding = (PFNGLUNIFORMBLOCKBINDINGPROC)load("glUniformBlockBinding");
    glBindBufferBase = (PFNGLBINDBUFFERBASEPROC)load("glBindBufferBase");
    glBindBufferRange = (PFNGLBINDBUFFERRANGEPROC)load("glBindBufferRange");
    glDrawArraysInstanced = (PFNGLDRAWARRAYSINSTANCEDPROC)load("glDrawArraysInstanced");
    glDrawElementsInstanced = (PFNGLDRAWELEMENTSINSTANCEDPROC)load("glDrawElementsInstanced");
}

static void glad_load_gl33(GLADloadproc load) {
    glVertexAttribDivisor = (PFNGLVERTEXATTRIBDIVISORPROC)load("glVertexAttribDivisor");
    glGenSamplers = (PFNGLGENSAMPLERSPROC)load("glGenSamplers");
    glDeleteSamplers = (PFNGLDELETESAMPLERSPROC)load("glDeleteSamplers");
    glBindSampler = (PFNGLBINDSAMPLERPROC)load("glBindSampler");
    glSamplerParameteri = (PFNGLSAMPLERPARAMETERIPROC)load("glSamplerParameteri");
    glSamplerParameterf = (PFNGLSAMPLERPARAMETERFPROC)load("glSamplerParameterf");
}

static int glad_parse_version(const char* version_str, int* major, int* minor) {
    const char* p;
    if (!version_str) return 0;
    /* Skip any leading non-digit characters (e.g. "OpenGL ES") */
    p = version_str;
    while (*p && (*p < '0' || *p > '9')) p++;
    if (!*p) return 0;
    *major = 0;
    while (*p >= '0' && *p <= '9') {
        *major = *major * 10 + (*p - '0');
        p++;
    }
    if (*p == '.') p++;
    *minor = 0;
    while (*p >= '0' && *p <= '9') {
        *minor = *minor * 10 + (*p - '0');
        p++;
    }
    return 1;
}

int gladLoadGLLoader(GLADloadproc load) {
    const char* version_str;
    int major = 0, minor = 0;

    if (!load) return 0;

    /* We need glGetString first to determine the version */
    glGetString = (PFNGLGETSTRINGPROC)load("glGetString");
    if (!glGetString) return 0;

    version_str = (const char*)glGetString(GL_VERSION);
    if (!glad_parse_version(version_str, &major, &minor)) return 0;

    /* Check that we got at least GL 3.3 */
    if (major < 3 || (major == 3 && minor < 3)) return 0;

    /* Load all function groups up to GL 3.3 */
    glad_load_gl10(load);
    glad_load_gl11(load);
    glad_load_gl13(load);
    glad_load_gl14(load);
    glad_load_gl15(load);
    glad_load_gl20(load);
    glad_load_gl30(load);
    glad_load_gl31(load);
    glad_load_gl33(load);

    return 1;
}
